APT::FTPArchive::Release {
  Origin "liteadmin";
  Label "liteadmin";
  Suite "stable";
  Codename "stable";
  Components "main";
  Architectures "amd64 arm64 all";
  Description "LiteAdmin apt repository";
};