#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    mkdir -p /etc/liteadmin /var/lib/liteadmin/databases

    if [ ! -f /etc/liteadmin/config.json ]; then
        touch /etc/liteadmin/config.json
    fi

    # Symbolic links for the config files and storage directories
    ln -sfn /etc/liteadmin/config.json    /usr/share/liteadmin/config.json
    ln -sfn /var/lib/liteadmin/databases  /usr/share/liteadmin/databases

    chown www-data:www-data /etc/liteadmin/config.json
    chmod 640 /etc/liteadmin/config.json
    chown -R www-data:www-data /var/lib/liteadmin

    systemctl try-reload-or-restart 'php*-fpm.service' 2>/dev/null || true
fi

exit 0